services:
  - type: web
    name: quiz-management-api
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: quiz-db
          property: connectionString

databases:
  - name: quiz-db
    databaseName: quiz_management
    ipAllowList: []
    plan: starter
